// dans-util - single-header amalgamation
// version 0.2.0
//
// Generated by tools/amalgamate.py from the dans-util sources.
// Do not edit this file by hand; edit the sources under include/ and src/
// then regenerate with:  python tools/amalgamate.py
//
// In exactly one translation unit, define the implementation macro before
// including this header to compile the out-of-line function bodies:
//
//     #define DANS_UTIL_IMPLEMENTATION
//     #include <dans/dans_util.hpp>

#ifndef DANS_UTIL_AMALGAMATED_HPP
#define DANS_UTIL_AMALGAMATED_HPP

#define DANS_UTIL_VERSION "0.2.0"

// ==========================================================================
// vendored core: dans/types.hpp
// ==========================================================================
#ifndef DANS_CORE_INCLUDE_DANS_TYPES_HPP
#define DANS_CORE_INCLUDE_DANS_TYPES_HPP

#include <cstddef>
#include <cstdint>
#include <type_traits>
#if defined(__has_include) and __has_include(<stdfloat>)
#include <stdfloat>
#endif

namespace dans {
using usize = std::size_t;
using isize = std::ptrdiff_t;

using uptr = std::uintptr_t;
using iptr = std::intptr_t;

using u8 = std::uint8_t;
using u16 = std::uint16_t;
using u32 = std::uint32_t;
using u64 = std::uint64_t;

using i8 = std::int8_t;
using i16 = std::int16_t;
using i32 = std::int32_t;
using i64 = std::int64_t;

#if defined(__STDCPP_FLOAT32_T__) and defined(__STDCPP_FLOAT64_T__)
using f32 = std::float32_t;
using f64 = std::float64_t;
#else
using f32 = float;
using f64 = double;
#endif

static_assert(std::is_same_v<usize, decltype(sizeof(void *))>);
static_assert(
    std::is_same_v<isize, decltype(static_cast<int *>(nullptr) - static_cast<int *>(nullptr))>);

static_assert(sizeof(std::byte) == 1zu);

static_assert(sizeof(u8) == 1zu);
static_assert(sizeof(u16) == 2zu);
static_assert(sizeof(u32) == 4zu);
static_assert(sizeof(u64) == 8zu);

static_assert(sizeof(i8) == 1zu);
static_assert(sizeof(i16) == 2zu);
static_assert(sizeof(i32) == 4zu);
static_assert(sizeof(i64) == 8zu);

static_assert(sizeof(f32) == 4zu);
static_assert(sizeof(f64) == 8zu);

} // namespace dans

#endif // DANS_CORE_INCLUDE_DANS_TYPES_HPP

// ==========================================================================
// vendored core: dans/development_markers.hpp
// ==========================================================================
#ifndef DANS_CORE_INCLUDE_DANS_DEVELOPMENT_MARKERS_HPP
#define DANS_CORE_INCLUDE_DANS_DEVELOPMENT_MARKERS_HPP

#include <type_traits> // IWYU pragma: keep

#if defined(cpy)
#error "cpy marker macro is already defined"
#endif

#if defined(def)
#error "def marker macro is already defined"
#endif

#if defined(__clang__)
#define cpy [[clang::annotate("cpy")]]
#else
#define cpy
#endif

// Only use this on the auto for functions when using trailing return
#define def auto

namespace dans {
template <typename T>
[[nodiscard]] constexpr def copy(const T &value) -> std::remove_cvref_t<T> {
    return value;
}
} // namespace dans

#endif // DANS_CORE_INCLUDE_DANS_DEVELOPMENT_MARKERS_HPP

// ==========================================================================
// include/dans/overload.hpp
// ==========================================================================
#ifndef DANS_OVERLOAD_HPP
#define DANS_OVERLOAD_HPP

namespace dans
{
template <typename... Ts>
struct overload : Ts...
{
    using Ts::operator()...;
};

template <typename... Ts>
overload(Ts...) -> overload<Ts...>;
}  // namespace dans

#endif  // DANS_OVERLOAD_HPP

// ==========================================================================
// include/dans/lit.hpp
// ==========================================================================
#ifndef DANS_LIT_HPP
#define DANS_LIT_HPP

namespace dans::lit
{
[[nodiscard]] consteval def operator""_byte(unsigned long long n) -> u64
{
    return n;
}

[[nodiscard]] consteval def operator""_kib(unsigned long long n) -> u64
{
    return n * 1024ULL;
}

[[nodiscard]] consteval def operator""_mib(unsigned long long n) -> u64
{
    return n * 1024ULL * 1024ULL;
}

[[nodiscard]] consteval def operator""_gib(unsigned long long n) -> u64
{
    return n * 1024ULL * 1024ULL * 1024ULL;
}

[[nodiscard]] consteval def operator""_tib(unsigned long long n) -> u64
{
    return n * 1024ULL * 1024ULL * 1024ULL * 1024ULL;
}

[[nodiscard]] consteval def operator""_kb(unsigned long long n) -> u64
{
    return n * 1000ULL;
}

[[nodiscard]] consteval def operator""_mb(unsigned long long n) -> u64
{
    return n * 1000ULL * 1000ULL;
}

[[nodiscard]] consteval def operator""_gb(unsigned long long n) -> u64
{
    return n * 1000ULL * 1000ULL * 1000ULL;
}

[[nodiscard]] consteval def operator""_tb(unsigned long long n) -> u64
{
    return n * 1000ULL * 1000ULL * 1000ULL * 1000ULL;
}
}  // namespace dans::lit

#endif  // DANS_LIT_HPP

// ==========================================================================
// include/dans/math.hpp
// ==========================================================================
#include <algorithm>
#include <cassert>
#include <concepts>
#include <functional>
#include <limits>
#include <numbers>
#include <ranges>
#include <utility>

#ifndef DANS_MATH_HPP
#define DANS_MATH_HPP

namespace dans::math
{
inline constexpr auto pi = std::numbers::pi;
inline constexpr auto two_pi = 2.0 * pi;
inline constexpr auto tau = two_pi;
inline constexpr auto half_pi = pi / 2.0;
inline constexpr auto quarter_pi = pi / 4.0;
inline constexpr auto inv_pi = std::numbers::inv_pi;
inline constexpr auto e = std::numbers::e;
inline constexpr auto sqrt2 = std::numbers::sqrt2;
inline constexpr auto sqrt3 = std::numbers::sqrt3;
inline constexpr auto inv_sqrt3 = std::numbers::inv_sqrt3;
inline constexpr auto inv_sqrtpi = std::numbers::inv_sqrtpi;
inline constexpr auto ln2 = std::numbers::ln2;
inline constexpr auto ln10 = std::numbers::ln10;

template <typename T, typename U, typename V>
    requires requires(T x, U lo, V hi) {
        std::cmp_less_equal(lo, x);
        std::cmp_less_equal(x, hi);
        std::cmp_less_equal(lo, hi);
    }
[[nodiscard]] constexpr def in_interval(T x, U lo, V hi) -> bool
{
    assert(std::cmp_less_equal(lo, hi));
    return std::cmp_less_equal(lo, x) and std::cmp_less_equal(x, hi);
}

template <std::floating_point T>
[[nodiscard]] constexpr def in_interval(T x, T lo, T hi) -> bool
{
    assert(lo <= hi);
    return lo <= x and x <= hi;
}

template <std::floating_point T>
[[nodiscard]] constexpr def unlerp(T a, T b, T x) -> T
{
    return (x - a) / (b - a);
}

template <std::floating_point T>
[[nodiscard]] constexpr def remap(T x, T in_lo, T in_hi, T out_lo, T out_hi) -> T
{
    return out_lo + (x - in_lo) * (out_hi - out_lo) / (in_hi - in_lo);
}

template <std::floating_point T>
[[nodiscard]] constexpr def approx_equal(
    T a,
    T b,
    T abs_eps = std::numeric_limits<T>::epsilon() * T{100},
    T rel_eps = std::numeric_limits<T>::epsilon() * T{100}) -> bool
{
    if (a == b) return true;
    const auto diff = (a > b) ? (a - b) : (b - a);
    if (diff <= abs_eps) return true;
    const auto abs_a = (a < T{0}) ? -a : a;
    const auto abs_b = (b < T{0}) ? -b : b;
    return diff <= rel_eps * std::max(abs_a, abs_b);
}

template <std::floating_point T>
[[nodiscard]] constexpr def almost_zero(
    T x, T eps = std::numeric_limits<T>::epsilon() * T{100}) -> bool
{
    return ((x < T{0}) ? -x : x) <= eps;
}

template <std::integral T>
[[nodiscard]] constexpr def ceil_div(T a, T b) -> T
{
    assert(a >= T{0} and b > T{0});
    return a / b + (a % b != T{0} ? T{1} : T{0});
}

template <std::integral T>
[[nodiscard]] constexpr def round_up_to(T n, T multiple) -> T
{
    assert(n >= T{0} and multiple > T{0});
    return ceil_div(n, multiple) * multiple;
}

template <std::unsigned_integral T>
[[nodiscard]] constexpr def align_up(T value, T alignment) -> T
{
    assert(alignment > T{0} and (alignment & (alignment - T{1})) == T{0});
    return (value + alignment - T{1}) & ~(alignment - T{1});
}

template <std::ranges::input_range R>
    requires std::is_arithmetic_v<std::ranges::range_value_t<R>>
[[nodiscard]] constexpr def sum(const R& values) -> std::ranges::range_value_t<R>
{
    using T = std::ranges::range_value_t<R>;
    return std::ranges::fold_left(values, T{0}, std::plus{});
}

template <std::ranges::input_range R>
    requires std::is_arithmetic_v<std::ranges::range_value_t<R>>
[[nodiscard]] constexpr def mean(const R& values) -> f64
{
    assert(not std::ranges::empty(values));
    const auto total = std::ranges::fold_left(values, f64{0}, std::plus{});
    return total / static_cast<f64>(std::ranges::distance(values));
}
}  // namespace dans::math

#endif  // DANS_MATH_HPP

// ==========================================================================
// include/dans/stats.hpp
// ==========================================================================
#include <algorithm>
#include <cmath>
#include <ranges>
#include <span>
#include <type_traits>
#include <vector>

#ifndef DANS_STATS_HPP
#define DANS_STATS_HPP

namespace dans::stats
{
struct Summary
{
    usize count{};
    f64 mean{};
    f64 min{};
    f64 max{};
    f64 median{};
    f64 p90{};
    f64 p95{};
    f64 p99{};
    f64 stddev{};
};

template <typename T>
    requires std::is_arithmetic_v<T>
[[nodiscard]] def summarize(std::span<const T> values) -> Summary
{
    if (values.empty()) return Summary{};

    std::vector<f64> sorted{};
    sorted.reserve(values.size());
    for (const auto v : values) sorted.push_back(static_cast<f64>(v));
    std::ranges::sort(sorted);

    auto sum = 0.0;
    for (const auto v : sorted) sum += v;
    const auto mean = sum / static_cast<f64>(sorted.size());

    auto sq_sum = 0.0;
    for (const auto v : sorted)
    {
        const auto d = v - mean;
        sq_sum += d * d;
    }
    const auto stddev = std::sqrt(sq_sum / static_cast<f64>(sorted.size()));

    const auto percentile = [&](f64 p) -> f64
    {
        const auto rank = p * static_cast<f64>(sorted.size() - 1);
        const auto lo = static_cast<usize>(std::floor(rank));
        const auto hi = static_cast<usize>(std::ceil(rank));
        if (lo == hi) return sorted[lo];
        const auto frac = rank - static_cast<f64>(lo);
        return sorted[lo] * (1.0 - frac) + sorted[hi] * frac;
    };

    return Summary{
        .count = sorted.size(),
        .mean = mean,
        .min = sorted.front(),
        .max = sorted.back(),
        .median = percentile(0.5),
        .p90 = percentile(0.9),
        .p95 = percentile(0.95),
        .p99 = percentile(0.99),
        .stddev = stddev,
    };
}

template <typename T>
    requires std::is_arithmetic_v<T>
[[nodiscard]] def summarize(const std::vector<T>& values) -> Summary
{
    return summarize(std::span<const T>{values});
}
}  // namespace dans::stats

#endif  // DANS_STATS_HPP

// ==========================================================================
// include/dans/views.hpp
// ==========================================================================
#include <ranges>
#include <utility>
#include <version>

#ifndef DANS_VIEWS_HPP
#define DANS_VIEWS_HPP

namespace dans::views
{
using std::views::zip;

#if defined(__cpp_lib_ranges_enumerate) and __cpp_lib_ranges_enumerate >= 202302L
using std::views::enumerate;
#else
template <std::ranges::viewable_range R>
[[nodiscard]] constexpr def enumerate(R&& r) -> decltype(auto)
{
    return std::views::zip(std::views::iota(usize{0}), std::forward<R>(r));
}
#endif
}  // namespace dans::views

#endif  // DANS_VIEWS_HPP

// ==========================================================================
// include/dans/dev.hpp
// ==========================================================================
#include <string_view>
#include <utility>

#ifndef DANS_DEV_HPP
#define DANS_DEV_HPP

namespace dans::dev
{
[[noreturn]] def panic_impl(std::string_view msg, std::string_view file, int line) -> void;

template <typename F>
class Defer
{
  public:
    explicit Defer(F func) : func_{std::move(func)}
    {
    }
    ~Defer()
    {
        func_();
    }
    Defer(const Defer&) = delete;
    Defer(Defer&&) = delete;
    def operator=(const Defer&) -> Defer& = delete;
    def operator=(Defer&&) -> Defer& = delete;

  private:
    F func_;
};

template <typename F>
Defer(F) -> Defer<F>;

}  // namespace dans::dev

#define DANS_PANIC(msg) ::dans::dev::panic_impl((msg), __FILE__, __LINE__)

#endif  // DANS_DEV_HPP

// ==========================================================================
// include/dans/str.hpp
// ==========================================================================
#include <concepts>
#include <ranges>
#include <string>
#include <string_view>
#include <vector>

#ifndef DANS_STR_HPP
#define DANS_STR_HPP

namespace dans::str
{
inline constexpr std::string_view default_whitespace{" \t\n\r\f\v"};

[[nodiscard]] def split(std::string_view text, char delim) -> std::vector<std::string_view>;

[[nodiscard]] constexpr def ltrim(
    std::string_view text, std::string_view chars = default_whitespace) -> std::string_view
{
    const auto pos = text.find_first_not_of(chars);
    if (pos == std::string_view::npos) return std::string_view{};
    return text.substr(pos);
}

[[nodiscard]] constexpr def rtrim(
    std::string_view text, std::string_view chars = default_whitespace) -> std::string_view
{
    const auto pos = text.find_last_not_of(chars);
    if (pos == std::string_view::npos) return std::string_view{};
    return text.substr(0, pos + 1);
}

[[nodiscard]] constexpr def trim(
    std::string_view text, std::string_view chars = default_whitespace) -> std::string_view
{
    return rtrim(ltrim(text, chars), chars);
}

template <std::ranges::input_range R>
    requires std::convertible_to<std::ranges::range_value_t<R>, std::string_view>
[[nodiscard]] def join(R&& range, std::string_view sep) -> std::string
{
    std::string out{};
    auto first = true;
    for (const std::string_view part : range)
    {
        if (not first) out += sep;
        out += part;
        first = false;
    }
    return out;
}

}  // namespace dans::str

#endif  // DANS_STR_HPP

// ==========================================================================
// include/dans/fmt.hpp
// ==========================================================================
#include <cstddef>
#include <span>
#include <string>

#ifndef DANS_FMT_HPP
#define DANS_FMT_HPP

namespace dans::fmt
{
[[nodiscard]] def format_bytes_binary(u64 bytes) -> std::string;
[[nodiscard]] def format_bytes_decimal(u64 bytes) -> std::string;
[[nodiscard]] def hex_dump(std::span<const std::byte> bytes) -> std::string;
}  // namespace dans::fmt

#endif  // DANS_FMT_HPP

// ==========================================================================
// include/dans/env.hpp
// ==========================================================================
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>

#ifndef DANS_ENV_HPP
#define DANS_ENV_HPP

namespace dans::env
{
[[nodiscard]] def get(std::string_view name) -> std::optional<std::string>;
[[nodiscard]] def get_int(std::string_view name) -> std::optional<i64>;
[[nodiscard]] def get_bool(std::string_view name) -> std::optional<bool>;
[[nodiscard]] def get_path(std::string_view name) -> std::optional<std::filesystem::path>;
}  // namespace dans::env

#endif  // DANS_ENV_HPP

// ==========================================================================
// include/dans/random.hpp
// ==========================================================================
#include <concepts>
#include <random>

#ifndef DANS_RANDOM_HPP
#define DANS_RANDOM_HPP

namespace dans::random
{
[[nodiscard]] def rng() -> std::mt19937_64&;
def seed(u64 value) -> void;

template <std::integral T>
[[nodiscard]] def int_in(T lo, T hi) -> T
{
    std::uniform_int_distribution<T> dist{lo, hi};
    return dist(rng());
}

template <std::floating_point T = f64>
[[nodiscard]] def float_in(T lo, T hi) -> T
{
    std::uniform_real_distribution<T> dist{lo, hi};
    return dist(rng());
}

template <std::floating_point T = f64>
[[nodiscard]] def normal(T mean = T{0}, T stddev = T{1}) -> T
{
    std::normal_distribution<T> dist{mean, stddev};
    return dist(rng());
}
}  // namespace dans::random

#endif  // DANS_RANDOM_HPP

// ==========================================================================
// include/dans/chrono.hpp
// ==========================================================================
#include <chrono>
#include <print>
#include <string>
#include <string_view>
#include <vector>

#ifndef DANS_CHRONO_HPP
#define DANS_CHRONO_HPP

namespace dans::chrono
{
[[nodiscard]] def format_seconds(std::chrono::duration<f64> dur, bool show_milliseconds = false)
    -> std::string;

class ScopeTimer
{
    using Clock = std::chrono::steady_clock;

  public:
    explicit ScopeTimer(std::string_view name, bool print_millis = false)
        : name_{name}, start_{Clock::now()}, print_millis_{print_millis}
    {
    }
    ~ScopeTimer()
    {
        try
        {
            const std::chrono::duration<f64> dur{Clock::now() - start_};
            std::println("{} finished in {}.", name_, format_seconds(dur, print_millis_));
        }
        catch (...)
        {
        }
    }
    ScopeTimer(const ScopeTimer&) = delete;
    ScopeTimer(ScopeTimer&&) = delete;
    def operator=(const ScopeTimer&) -> ScopeTimer& = delete;
    def operator=(ScopeTimer&&) -> ScopeTimer& = delete;

  private:
    std::string_view name_{};
    std::chrono::time_point<Clock> start_{};
    bool print_millis_{false};
};

class StopWatch
{
    using Clock = std::chrono::steady_clock;
    static constexpr usize initial_capacity{4};

  public:
    StopWatch()
    {
        durations_.reserve(initial_capacity);
    }

    def start() -> void
    {
        if (running_) DANS_PANIC("StopWatch::start() called while already running");
        start_time_ = Clock::now();
        running_ = true;
    }

    def stop() -> void
    {
        if (not running_) DANS_PANIC("StopWatch::stop() called without prior start()");
        const std::chrono::duration<f64> elapsed{Clock::now() - start_time_};
        durations_.push_back(elapsed.count());
        running_ = false;
    }

    def abort() -> void
    {
        running_ = false;
    }

    def clear() -> void
    {
        durations_.clear();
        running_ = false;
    }

    [[nodiscard]] def durations() const -> const std::vector<f64>&
    {
        return durations_;
    }

    [[nodiscard]] def is_running() const -> bool
    {
        return running_;
    }

  private:
    std::vector<f64> durations_{};
    std::chrono::time_point<Clock> start_time_{};
    bool running_{false};
};

}  // namespace dans::chrono

#endif  // DANS_CHRONO_HPP

// ==========================================================================
// include/dans/util.hpp
// ==========================================================================
#ifndef DANS_UTIL_HPP
#define DANS_UTIL_HPP

namespace dans::util
{
inline constexpr auto version = "0.2.0";
}  // namespace dans::util

#endif  // DANS_UTIL_HPP

#endif  // DANS_UTIL_AMALGAMATED_HPP

#ifdef DANS_UTIL_IMPLEMENTATION
#ifndef DANS_UTIL_IMPLEMENTATION_DONE
#define DANS_UTIL_IMPLEMENTATION_DONE

// ==========================================================================
// src/dev.cpp
// ==========================================================================
#include <cstdio>
#include <cstdlib>
#include <print>
#include <string_view>

namespace dans::dev
{
[[noreturn]] def panic_impl(std::string_view msg, std::string_view file, int line) -> void
{
    std::println(stderr, "PANIC at {}:{}: {}", file, line, msg);
    std::abort();
}
}  // namespace dans::dev

// ==========================================================================
// src/str.cpp
// ==========================================================================
#include <string_view>
#include <vector>

namespace dans::str
{
[[nodiscard]] def split(std::string_view text, char delim) -> std::vector<std::string_view>
{
    std::vector<std::string_view> out{};
    auto left = 0zu;
    while (true)
    {
        const auto pos = text.find(delim, left);
        if (pos == std::string_view::npos) break;
        out.push_back(text.substr(left, pos - left));
        left = pos + 1;
    }
    out.push_back(text.substr(left));
    return out;
}
}  // namespace dans::str

// ==========================================================================
// src/fmt.cpp
// ==========================================================================
#include <array>
#include <cstddef>
#include <format>
#include <iterator>
#include <span>
#include <string>
#include <string_view>

namespace dans::fmt
{
namespace
{
[[nodiscard]] def format_bytes_with(
    u64 bytes, f64 divisor, const std::array<std::string_view, 7>& suffixes) -> std::string
{
    auto value = static_cast<f64>(bytes);
    auto index = 0zu;
    while (value >= divisor and index + 1 < suffixes.size())
    {
        value /= divisor;
        ++index;
    }
    if (index == 0) return std::format("{} {}", bytes, suffixes[0]);

    auto formatted = std::format("{:.2f}", value);
    while (formatted.back() == '0') formatted.pop_back();
    if (formatted.back() == '.') formatted.pop_back();
    return std::format("{} {}", formatted, suffixes[index]);
}
}  // namespace

[[nodiscard]] def format_bytes_binary(u64 bytes) -> std::string
{
    constexpr std::array<std::string_view, 7> suffixes{
        "B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB"};
    return format_bytes_with(bytes, 1024.0, suffixes);
}

[[nodiscard]] def format_bytes_decimal(u64 bytes) -> std::string
{
    constexpr std::array<std::string_view, 7> suffixes{
        "B", "KB", "MB", "GB", "TB", "PB", "EB"};
    return format_bytes_with(bytes, 1000.0, suffixes);
}

[[nodiscard]] def hex_dump(std::span<const std::byte> bytes) -> std::string
{
    constexpr auto bytes_per_line = 16zu;

    std::string out{};
    out.reserve((bytes.size() / bytes_per_line + 1) * 80);

    for (auto offset = 0zu; offset < bytes.size(); offset += bytes_per_line)
    {
        std::format_to(std::back_inserter(out), "{:08x}  ", offset);

        for (auto i = 0zu; i < bytes_per_line; ++i)
        {
            if (offset + i < bytes.size())
            {
                std::format_to(
                    std::back_inserter(out),
                    "{:02x} ",
                    static_cast<u32>(bytes[offset + i]));
            }
            else
            {
                out += "   ";
            }
            if (i == 7) out += ' ';
        }

        out += " |";
        for (auto i = 0zu; i < bytes_per_line; ++i)
        {
            if (offset + i >= bytes.size()) break;
            const auto b = static_cast<u8>(bytes[offset + i]);
            out += (b >= 0x20 and b < 0x7f) ? static_cast<char>(b) : '.';
        }
        out += "|\n";
    }
    return out;
}
}  // namespace dans::fmt

// ==========================================================================
// src/env.cpp
// ==========================================================================
#include <algorithm>
#include <array>
#include <cctype>
#include <charconv>
#include <cstdlib>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>
#include <system_error>

namespace dans::env
{
[[nodiscard]] def get(std::string_view name) -> std::optional<std::string>
{
    const std::string name_str{name};
    const auto* raw = std::getenv(name_str.c_str());
    if (raw == nullptr) return std::nullopt;
    return std::string{raw};
}

[[nodiscard]] def get_int(std::string_view name) -> std::optional<i64>
{
    const auto value = get(name);
    if (not value.has_value() or value->empty()) return std::nullopt;
    i64 result{};
    const auto* begin = value->data();
    const auto* end = value->data() + value->size();
    const auto [ptr, ec] = std::from_chars(begin, end, result);
    if (ec != std::errc{} or ptr != end) return std::nullopt;
    return result;
}

[[nodiscard]] def get_bool(std::string_view name) -> std::optional<bool>
{
    const auto value = get(name);
    if (not value.has_value() or value->empty()) return std::nullopt;

    std::string normalized{};
    normalized.reserve(value->size());
    for (const auto c : *value)
    {
        normalized.push_back(
            static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    }

    constexpr std::array<std::string_view, 4> truthy{"1", "true", "yes", "on"};
    constexpr std::array<std::string_view, 4> falsy{"0", "false", "no", "off"};
    if (std::ranges::find(truthy, normalized) != truthy.end()) return true;
    if (std::ranges::find(falsy, normalized) != falsy.end()) return false;
    return std::nullopt;
}

[[nodiscard]] def get_path(std::string_view name) -> std::optional<std::filesystem::path>
{
    const auto value = get(name);
    if (not value.has_value() or value->empty()) return std::nullopt;
    return std::filesystem::path{*value};
}
}  // namespace dans::env

// ==========================================================================
// src/random.cpp
// ==========================================================================
#include <random>

namespace dans::random
{
[[nodiscard]] def rng() -> std::mt19937_64&
{
    thread_local std::mt19937_64 engine{std::random_device{}()};
    return engine;
}

def seed(u64 value) -> void
{
    rng().seed(value);
}
}  // namespace dans::random

// ==========================================================================
// src/chrono.cpp
// ==========================================================================
#include <chrono>
#include <format>
#include <string>
#include <string_view>

namespace dans::chrono
{
[[nodiscard]] def format_seconds(std::chrono::duration<f64> dur, bool show_milliseconds)
    -> std::string
{
    const auto is_negative = dur < std::chrono::duration<f64>::zero();
    const auto positive_duration = is_negative ? -dur : dur;

    using Msec = std::chrono::milliseconds;
    constexpr Msec::rep ms_per_second{1000};
    constexpr Msec::rep ms_per_minute{ms_per_second * 60};
    constexpr Msec::rep ms_per_hour{ms_per_minute * 60};
    constexpr Msec::rep ms_per_day{ms_per_hour * 24};

    auto remaining = std::chrono::duration_cast<Msec>(positive_duration).count();

    const auto days = remaining / ms_per_day;
    remaining %= ms_per_day;
    const auto hours = remaining / ms_per_hour;
    remaining %= ms_per_hour;
    const auto minutes = remaining / ms_per_minute;
    remaining %= ms_per_minute;
    const auto seconds = remaining / ms_per_second;
    const auto milliseconds = remaining % ms_per_second;

    std::string result{};
    auto started = false;

    const auto append_time_unit = [&](Msec::rep value, std::string_view name) -> void
    {
        if (not started and value == 0) return;
        if (not result.empty()) result += ' ';
        result += std::format("{} {}{}", value, name, value == 1 ? "" : "s");
        started = true;
    };
    append_time_unit(days, "day");
    append_time_unit(hours, "hour");
    append_time_unit(minutes, "minute");
    append_time_unit(seconds, "second");
    if (show_milliseconds) append_time_unit(milliseconds, "millisecond");

    if (not started) result = show_milliseconds ? "0 milliseconds" : "0 seconds";

    if (is_negative) return std::format("-{}", result);
    return result;
}
}  // namespace dans::chrono

// ==========================================================================
// src/util.cpp
// ==========================================================================
namespace dans::util
{
static_assert(sizeof(usize) >= sizeof(void*));
}  // namespace dans::util

#endif  // DANS_UTIL_IMPLEMENTATION_DONE
#endif  // DANS_UTIL_IMPLEMENTATION

